# Generated by Django 5.1.3 on 2025-08-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_origin_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
