# Generated by Django 5.1.3 on 2025-08-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_public_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
