# Generated by Django 5.1.3 on 2025-08-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_activity_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='nominatim', max_length=50)),
                ('query', models.CharField(blank=True, max_length=200)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'external_id'], name='trips_exter_source_78b5a6_idx'), models.Index(fields=['name', 'country'], name='trips_exter_name_9c1899_idx')],
            },
        ),
    ]
