# Generated by Django 5.1.3 on 2025-08-11 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_activity_updated_at_trip_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizedrec',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalizedrec',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='personalizedrec',
            index=models.Index(fields=['city', 'country'], name='trips_perso_city_459597_idx'),
        ),
    ]
